name: zz Plan Terraform Deployment
on:
  workflow_call:
    inputs:
      tf_version: 
        description: 'The version of Terraform to use'
        default: '1.5.3'
        type: string
      aws_region:
        description: 'The AWS region to use by default'
        default: 'us-east-1'
        type: string
      working_directory:
        description: 'The directory to run commands in'
        default: 'dev'
        required: true
        type: string
      event_name:
        description: 'The name of the event that called the workflow.'
        required: false
        type: string

env:
  TF_PLAN_PATH: ${{github.workspace}}/${{ inputs.working_directory }}/file-${{ github.sha }}.txt

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}
      - name: Terraform Init
        id: init
        run: touch $TF_PLAN_PATH

      - name: Upload Plan Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: $TF_PLAN_PATH
          name: file-${{ github.sha }}.txt