name: zz Validate Terraform Code
#env:
#  TF_VERSION: 1.5.3

on:
  workflow_call:
    inputs:
      tf_version: 
        description: 'The version of Terraform to use'
        default: '1.5.3'
        type: string
      working_directory:
        description: 'The directory to run commands in'
        default: 'dev'
        required: true
        type: string
    # secrets:
    #   git_account_token:
    #     required: true
    #   git_repo_token:
    #     required: true

jobs:
  tflint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code
      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: latest
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint --format=compact --minimum-failure-severity=error

  tfsec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v3
      - name: TFSec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: -e AWS007 #--soft-fail
          github_token: ${{ secrets.GITHUB_TOKEN }} # git_repo_token }}

  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}
      - name: Configure AWS credentials from shared services account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772158751016:role/github-actions-role
          aws-region: us-east-1
      - name: Terraform Init
        id: init
        run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://foo:${ACCESS_TOKEN}@github.com/Pizza-Nova".insteadOf "https://github.com/Pizza-Nova"
          git config --global advice.detachedHead false
          terraform init
        env:
          ACCESS_TOKEN: ${{ secrets.TEMP_TOKEN }} #git_account_token }}
          AWS_REGION: ${{ inputs.aws_region }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Validate
        id: validate
        run: |
          pwd
          terraform validate -no-color
